# LinusB parts
cp LinusB/0-hopper-seq-stopper.stl           TO_PRINT/
cp LinusB/1-sequentializer-ilc-bottom.stl    TO_PRINT/
cp LinusB/1-sequentializer-ilc-top.stl       TO_PRINT/
cp LinusB/1-sequentializer-motor-holder.stl  TO_PRINT/
cp LinusB/3-analyzer-base.stl                TO_PRINT/
cp LinusB/3-analyzer-exit-base.stl           TO_PRINT/
cp LinusB/3-analyzer-exit-tube.stl           TO_PRINT/
cp LinusB/3-analyzer-ilc-bottom.stl          TO_PRINT/
cp LinusB/3-analyzer-ilc-corner.stl          TO_PRINT/
cp LinusB/3-analyzer-ilc-top.stl             TO_PRINT/
cp LinusB/3-analyzer-separation-arm.stl      TO_PRINT/
cp LinusB/3-analyzer-servo-holder.stl        TO_PRINT/
cp LinusB/3-analyzer-top-alignment.stl       TO_PRINT/
cp LinusB/4-dispatcher-ilc-bottom.stl        TO_PRINT/
cp LinusB/4-dispatcher-ilc-corner.stl        TO_PRINT/
cp LinusB/4-dispatcher-ilc-top.stl           TO_PRINT/
cp LinusB/4-dispatcher-tube-alignment.stl    TO_PRINT/
cp LinusB/4-dispatcher-tubehalf-1.stl        TO_PRINT/
cp LinusB/4-dispatcher-tubehalf-2.stl        TO_PRINT/
cp LinusB/5-outputs-ilc-corner.stl           TO_PRINT/
cp LinusB/5-outputs-ilc-top.stl              TO_PRINT/

# RichA777 parts
cp RichA777/0-hopper-seq-plate-4_holes_modified.stl TO_PRINT/
cp RichA777/Hopper_Modified_Cleaned_up.stl          TO_PRINT/
cp RichA777/Sequencer_base_modified.stl             TO_PRINT/

# HEN3DRIK parts
cp HEN3DRIK/*.stl TO_PRINT/